### ISSUE TITLE
Add recommended CSS for Lenis smooth scroll

### ISSUE THREAD

**Issue by CHR-onicles** [CHR-onicles/rtsc-template#623]
```css
    // Recommended CSS for Lenis
    html.lenis, html.lenis body {
        height: auto;
    }

    .lenis.lenis-smooth {
        scroll-behavior: auto !important;
    }

    .lenis.lenis-smooth [data-lenis-prevent] {
        overscroll-behavior: contain;
    }

    .lenis.lenis-stopped {
        overflow: hidden;
    }

    .lenis.lenis-scrolling iframe {
        pointer-events: none;
    }
```
